export let array = [
  {
    id: 1,
    date: "2024-01-05",
    time: "01:43:55",
    level: "INFO",
    message:
      "Generator percentage changed from 0% to 60% using 'generator/update' endpoint.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: "Red is watching.",
    dateCommented: "2024-01-05",
    timeCommented: "01:44:26",
  },
  {
    id: 2,
    date: "2024-01-05",
    time: "01:43:58",
    level: "INFO",
    message:
      "Generator percentage requested using 'generator/percentage' endpoint. Percentage was 60%.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 3,
    date: "2024-01-05",
    time: "01:44:06",
    level: "INFO",
    message:
      "Substations values changed from 0 MW, 0 MW, and 0 MW to 5 MW, 4 MW, and 1 MW using 'substations/update' endpoint.",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 4,
    date: "2024-01-05",
    time: "01:44:08",
    level: "INFO",
    message:
      "Substations values requested using 'substations/values' endpoint. Values were 5 MW, 4 MW, and 1 MW",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 5,
    date: "2024-01-05",
    time: "01:44:37",
    level: "INFO",
    message: "MANUAL LOG: Log4j",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 1,
    date: "2024-01-05",
    time: "01:43:55",
    level: "INFO",
    message:
      "Generator percentage changed from 0% to 60% using 'generator/update' endpoint.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: "Red is watching.",
    dateCommented: "2024-01-05",
    timeCommented: "01:44:26",
  },
  {
    id: 2,
    date: "2024-01-05",
    time: "01:43:58",
    level: "INFO",
    message:
      "Generator percentage requested using 'generator/percentage' endpoint. Percentage was 60%.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 3,
    date: "2024-01-05",
    time: "01:44:06",
    level: "INFO",
    message:
      "Substations values changed from 0 MW, 0 MW, and 0 MW to 5 MW, 4 MW, and 1 MW using 'substations/update' endpoint.",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 4,
    date: "2024-01-05",
    time: "01:44:08",
    level: "INFO",
    message:
      "Substations values requested using 'substations/values' endpoint. Values were 5 MW, 4 MW, and 1 MW",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 1,
    date: "2024-01-05",
    time: "01:43:55",
    level: "INFO",
    message:
      "Generator percentage changed from 0% to 60% using 'generator/update' endpoint.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: "Red is watching.",
    dateCommented: "2024-01-05",
    timeCommented: "01:44:26",
  },
  {
    id: 2,
    date: "2024-01-05",
    time: "01:43:58",
    level: "INFO",
    message:
      "Generator percentage requested using 'generator/percentage' endpoint. Percentage was 60%.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 3,
    date: "2024-01-05",
    time: "01:44:06",
    level: "INFO",
    message:
      "Substations values changed from 0 MW, 0 MW, and 0 MW to 5 MW, 4 MW, and 1 MW using 'substations/update' endpoint.",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 4,
    date: "2024-01-05",
    time: "01:44:08",
    level: "INFO",
    message:
      "Substations values requested using 'substations/values' endpoint. Values were 5 MW, 4 MW, and 1 MW",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 1,
    date: "2024-01-05",
    time: "01:43:55",
    level: "INFO",
    message:
      "Generator percentage changed from 0% to 60% using 'generator/update' endpoint.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: "Red is watching.",
    dateCommented: "2024-01-05",
    timeCommented: "01:44:26",
  },
  {
    id: 2,
    date: "2024-01-05",
    time: "01:43:58",
    level: "INFO",
    message:
      "Generator percentage requested using 'generator/percentage' endpoint. Percentage was 60%.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 3,
    date: "2024-01-05",
    time: "01:44:06",
    level: "INFO",
    message:
      "Substations values changed from 0 MW, 0 MW, and 0 MW to 5 MW, 4 MW, and 1 MW using 'substations/update' endpoint.",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 4,
    date: "2024-01-05",
    time: "01:44:08",
    level: "INFO",
    message:
      "Substations values requested using 'substations/values' endpoint. Values were 5 MW, 4 MW, and 1 MW",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 1,
    date: "2024-01-05",
    time: "01:43:55",
    level: "INFO",
    message:
      "Generator percentage changed from 0% to 60% using 'generator/update' endpoint.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: "Red is watching.",
    dateCommented: "2024-01-05",
    timeCommented: "01:44:26",
  },
  {
    id: 2,
    date: "2024-01-05",
    time: "01:43:58",
    level: "INFO",
    message:
      "Generator percentage requested using 'generator/percentage' endpoint. Percentage was 60%.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 3,
    date: "2024-01-05",
    time: "01:44:06",
    level: "INFO",
    message:
      "Substations values changed from 0 MW, 0 MW, and 0 MW to 5 MW, 4 MW, and 1 MW using 'substations/update' endpoint.",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 4,
    date: "2024-01-05",
    time: "01:44:08",
    level: "INFO",
    message:
      "Substations values requested using 'substations/values' endpoint. Values were 5 MW, 4 MW, and 1 MW",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 1,
    date: "2024-01-05",
    time: "01:43:55",
    level: "INFO",
    message:
      "Generator percentage changed from 0% to 60% using 'generator/update' endpoint.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: "Red is watching.",
    dateCommented: "2024-01-05",
    timeCommented: "01:44:26",
  },
  {
    id: 2,
    date: "2024-01-05",
    time: "01:43:58",
    level: "INFO",
    message:
      "Generator percentage requested using 'generator/percentage' endpoint. Percentage was 60%.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 3,
    date: "2024-01-05",
    time: "01:44:06",
    level: "INFO",
    message:
      "Substations values changed from 0 MW, 0 MW, and 0 MW to 5 MW, 4 MW, and 1 MW using 'substations/update' endpoint.",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 4,
    date: "2024-01-05",
    time: "01:44:08",
    level: "INFO",
    message:
      "Substations values requested using 'substations/values' endpoint. Values were 5 MW, 4 MW, and 1 MW",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 1,
    date: "2024-01-05",
    time: "01:43:55",
    level: "INFO",
    message:
      "Generator percentage changed from 0% to 60% using 'generator/update' endpoint.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: "Red is watching.",
    dateCommented: "2024-01-05",
    timeCommented: "01:44:26",
  },
  {
    id: 2,
    date: "2024-01-05",
    time: "01:43:58",
    level: "INFO",
    message:
      "Generator percentage requested using 'generator/percentage' endpoint. Percentage was 60%.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 3,
    date: "2024-01-05",
    time: "01:44:06",
    level: "INFO",
    message:
      "Substations values changed from 0 MW, 0 MW, and 0 MW to 5 MW, 4 MW, and 1 MW using 'substations/update' endpoint.",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 4,
    date: "2024-01-05",
    time: "01:44:08",
    level: "INFO",
    message:
      "Substations values requested using 'substations/values' endpoint. Values were 5 MW, 4 MW, and 1 MW",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 1,
    date: "2024-01-05",
    time: "01:43:55",
    level: "INFO",
    message:
      "Generator percentage changed from 0% to 60% using 'generator/update' endpoint.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: "Red is watching.",
    dateCommented: "2024-01-05",
    timeCommented: "01:44:26",
  },
  {
    id: 2,
    date: "2024-01-05",
    time: "01:43:58",
    level: "INFO",
    message:
      "Generator percentage requested using 'generator/percentage' endpoint. Percentage was 60%.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 3,
    date: "2024-01-05",
    time: "01:44:06",
    level: "INFO",
    message:
      "Substations values changed from 0 MW, 0 MW, and 0 MW to 5 MW, 4 MW, and 1 MW using 'substations/update' endpoint.",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 4,
    date: "2024-01-05",
    time: "01:44:08",
    level: "INFO",
    message:
      "Substations values requested using 'substations/values' endpoint. Values were 5 MW, 4 MW, and 1 MW",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 1,
    date: "2024-01-05",
    time: "01:43:55",
    level: "INFO",
    message:
      "Generator percentage changed from 0% to 60% using 'generator/update' endpoint.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: "Red is watching.",
    dateCommented: "2024-01-05",
    timeCommented: "01:44:26",
  },
  {
    id: 2,
    date: "2024-01-05",
    time: "01:43:58",
    level: "INFO",
    message:
      "Generator percentage requested using 'generator/percentage' endpoint. Percentage was 60%.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 3,
    date: "2024-01-05",
    time: "01:44:06",
    level: "INFO",
    message:
      "Substations values changed from 0 MW, 0 MW, and 0 MW to 5 MW, 4 MW, and 1 MW using 'substations/update' endpoint.",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 4,
    date: "2024-01-05",
    time: "01:44:08",
    level: "INFO",
    message:
      "Substations values requested using 'substations/values' endpoint. Values were 5 MW, 4 MW, and 1 MW",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 1,
    date: "2024-01-05",
    time: "01:43:55",
    level: "INFO",
    message:
      "Generator percentage changed from 0% to 60% using 'generator/update' endpoint.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: "Red is watching.",
    dateCommented: "2024-01-05",
    timeCommented: "01:44:26",
  },
  {
    id: 2,
    date: "2024-01-05",
    time: "01:43:58",
    level: "INFO",
    message:
      "Generator percentage requested using 'generator/percentage' endpoint. Percentage was 60%.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 3,
    date: "2024-01-05",
    time: "01:44:06",
    level: "INFO",
    message:
      "Substations values changed from 0 MW, 0 MW, and 0 MW to 5 MW, 4 MW, and 1 MW using 'substations/update' endpoint.",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 4,
    date: "2024-01-05",
    time: "01:44:08",
    level: "INFO",
    message:
      "Substations values requested using 'substations/values' endpoint. Values were 5 MW, 4 MW, and 1 MW",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 1,
    date: "2024-01-05",
    time: "01:43:55",
    level: "INFO",
    message:
      "Generator percentage changed from 0% to 60% using 'generator/update' endpoint.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: "Red is watching.",
    dateCommented: "2024-01-05",
    timeCommented: "01:44:26",
  },
  {
    id: 2,
    date: "2024-01-05",
    time: "01:43:58",
    level: "INFO",
    message:
      "Generator percentage requested using 'generator/percentage' endpoint. Percentage was 60%.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 3,
    date: "2024-01-05",
    time: "01:44:06",
    level: "INFO",
    message:
      "Substations values changed from 0 MW, 0 MW, and 0 MW to 5 MW, 4 MW, and 1 MW using 'substations/update' endpoint.",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 4,
    date: "2024-01-05",
    time: "01:44:08",
    level: "INFO",
    message:
      "Substations values requested using 'substations/values' endpoint. Values were 5 MW, 4 MW, and 1 MW",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 1,
    date: "2024-01-05",
    time: "01:43:55",
    level: "INFO",
    message:
      "Generator percentage changed from 0% to 60% using 'generator/update' endpoint.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: "Red is watching.",
    dateCommented: "2024-01-05",
    timeCommented: "01:44:26",
  },
  {
    id: 2,
    date: "2024-01-05",
    time: "01:43:58",
    level: "INFO",
    message:
      "Generator percentage requested using 'generator/percentage' endpoint. Percentage was 60%.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 3,
    date: "2024-01-05",
    time: "01:44:06",
    level: "INFO",
    message:
      "Substations values changed from 0 MW, 0 MW, and 0 MW to 5 MW, 4 MW, and 1 MW using 'substations/update' endpoint.",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 4,
    date: "2024-01-05",
    time: "01:44:08",
    level: "INFO",
    message:
      "Substations values requested using 'substations/values' endpoint. Values were 5 MW, 4 MW, and 1 MW",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 1,
    date: "2024-01-05",
    time: "01:43:55",
    level: "INFO",
    message:
      "Generator percentage changed from 0% to 60% using 'generator/update' endpoint.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: "Red is watching.",
    dateCommented: "2024-01-05",
    timeCommented: "01:44:26",
  },
  {
    id: 2,
    date: "2024-01-05",
    time: "01:43:58",
    level: "INFO",
    message:
      "Generator percentage requested using 'generator/percentage' endpoint. Percentage was 60%.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 3,
    date: "2024-01-05",
    time: "01:44:06",
    level: "INFO",
    message:
      "Substations values changed from 0 MW, 0 MW, and 0 MW to 5 MW, 4 MW, and 1 MW using 'substations/update' endpoint.",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 4,
    date: "2024-01-05",
    time: "01:44:08",
    level: "INFO",
    message:
      "Substations values requested using 'substations/values' endpoint. Values were 5 MW, 4 MW, and 1 MW",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
];
