export let array = [
  {
    id: 1,
    date: "2024-01-05",
    time: "01:43:55",
    level: "INFO",
    message:
      "Generator percentage changed from 0% to 60% using 'generator/update' endpoint.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: "Red is watching.",
    dateCommented: "2024-01-05",
    timeCommented: "01:44:26",
  },
  {
    id: 2,
    date: "2024-01-05",
    time: "01:43:58",
    level: "INFO",
    message:
      "Generator percentage requested using 'generator/percentage' endpoint. Percentage was 60%.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 3,
    date: "2024-01-05",
    time: "01:44:06",
    level: "INFO",
    message:
      "Substations values changed from 0 MW, 0 MW, and 0 MW to 5 MW, 4 MW, and 1 MW using 'substations/update' endpoint.",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 4,
    date: "2024-01-05",
    time: "01:44:08",
    level: "INFO",
    message:
      "Substations values requested using 'substations/values' endpoint. Values were 5 MW, 4 MW, and 1 MW",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 5,
    date: "2024-01-05",
    time: "01:44:37",
    level: "INFO",
    message: "MANUAL LOG: Log4j",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 6,
    date: "2024-01-05",
    time: "01:43:55",
    level: "INFO",
    message:
      "Generator percentage changed from 0% to 60% using 'generator/update' endpoint.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: "Red is watching.",
    dateCommented: "2024-01-05",
    timeCommented: "01:44:26",
  },
  {
    id: 7,
    date: "2024-01-05",
    time: "01:43:58",
    level: "INFO",
    message:
      "Generator percentage requested using 'generator/percentage' endpoint. Percentage was 60%.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 8,
    date: "2024-01-05",
    time: "01:44:06",
    level: "INFO",
    message:
      "Substations values changed from 0 MW, 0 MW, and 0 MW to 5 MW, 4 MW, and 1 MW using 'substations/update' endpoint.",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 9,
    date: "2024-01-05",
    time: "01:44:08",
    level: "INFO",
    message:
      "Substations values requested using 'substations/values' endpoint. Values were 5 MW, 4 MW, and 1 MW",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 10,
    date: "2024-01-05",
    time: "01:43:55",
    level: "INFO",
    message:
      "Generator percentage changed from 0% to 60% using 'generator/update' endpoint.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: "Red is watching.",
    dateCommented: "2024-01-05",
    timeCommented: "01:44:26",
  },
  {
    id: 11,
    date: "2024-01-05",
    time: "01:43:58",
    level: "INFO",
    message:
      "Generator percentage requested using 'generator/percentage' endpoint. Percentage was 60%.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 12,
    date: "2024-01-05",
    time: "01:44:06",
    level: "INFO",
    message:
      "Substations values changed from 0 MW, 0 MW, and 0 MW to 5 MW, 4 MW, and 1 MW using 'substations/update' endpoint.",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 13,
    date: "2024-01-05",
    time: "01:44:08",
    level: "INFO",
    message:
      "Substations values requested using 'substations/values' endpoint. Values were 5 MW, 4 MW, and 1 MW",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 14,
    date: "2024-01-05",
    time: "01:43:55",
    level: "INFO",
    message:
      "Generator percentage changed from 0% to 60% using 'generator/update' endpoint.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: "Red is watching.",
    dateCommented: "2024-01-05",
    timeCommented: "01:44:26",
  },
  {
    id: 15,
    date: "2024-01-05",
    time: "01:43:58",
    level: "INFO",
    message:
      "Generator percentage requested using 'generator/percentage' endpoint. Percentage was 60%.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 16,
    date: "2024-01-05",
    time: "01:44:06",
    level: "INFO",
    message:
      "Substations values changed from 0 MW, 0 MW, and 0 MW to 5 MW, 4 MW, and 1 MW using 'substations/update' endpoint.",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 17,
    date: "2024-01-05",
    time: "01:44:08",
    level: "INFO",
    message:
      "Substations values requested using 'substations/values' endpoint. Values were 5 MW, 4 MW, and 1 MW",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 18,
    date: "2024-01-05",
    time: "01:43:55",
    level: "INFO",
    message:
      "Generator percentage changed from 0% to 60% using 'generator/update' endpoint.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: "Red is watching.",
    dateCommented: "2024-01-05",
    timeCommented: "01:44:26",
  },
  {
    id: 19,
    date: "2024-01-05",
    time: "01:43:58",
    level: "INFO",
    message:
      "Generator percentage requested using 'generator/percentage' endpoint. Percentage was 60%.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 20,
    date: "2024-01-05",
    time: "01:44:06",
    level: "INFO",
    message:
      "Substations values changed from 0 MW, 0 MW, and 0 MW to 5 MW, 4 MW, and 1 MW using 'substations/update' endpoint.",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 21,
    date: "2024-01-05",
    time: "01:44:08",
    level: "INFO",
    message:
      "Substations values requested using 'substations/values' endpoint. Values were 5 MW, 4 MW, and 1 MW",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 22,
    date: "2024-01-05",
    time: "01:43:55",
    level: "INFO",
    message:
      "Generator percentage changed from 0% to 60% using 'generator/update' endpoint.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: "Red is watching.",
    dateCommented: "2024-01-05",
    timeCommented: "01:44:26",
  },
  {
    id: 23,
    date: "2024-01-05",
    time: "01:43:58",
    level: "INFO",
    message:
      "Generator percentage requested using 'generator/percentage' endpoint. Percentage was 60%.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 24,
    date: "2024-01-05",
    time: "01:44:06",
    level: "INFO",
    message:
      "Substations values changed from 0 MW, 0 MW, and 0 MW to 5 MW, 4 MW, and 1 MW using 'substations/update' endpoint.",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 25,
    date: "2024-01-05",
    time: "01:44:08",
    level: "INFO",
    message:
      "Substations values requested using 'substations/values' endpoint. Values were 5 MW, 4 MW, and 1 MW",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 26,
    date: "2024-01-05",
    time: "01:43:55",
    level: "INFO",
    message:
      "Generator percentage changed from 0% to 60% using 'generator/update' endpoint.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: "Red is watching.",
    dateCommented: "2024-01-05",
    timeCommented: "01:44:26",
  },
  {
    id: 27,
    date: "2024-01-05",
    time: "01:43:58",
    level: "INFO",
    message:
      "Generator percentage requested using 'generator/percentage' endpoint. Percentage was 60%.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 28,
    date: "2024-01-05",
    time: "01:44:06",
    level: "INFO",
    message:
      "Substations values changed from 0 MW, 0 MW, and 0 MW to 5 MW, 4 MW, and 1 MW using 'substations/update' endpoint.",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 29,
    date: "2024-01-05",
    time: "01:44:08",
    level: "INFO",
    message:
      "Substations values requested using 'substations/values' endpoint. Values were 5 MW, 4 MW, and 1 MW",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 30,
    date: "2024-01-05",
    time: "01:43:55",
    level: "INFO",
    message:
      "Generator percentage changed from 0% to 60% using 'generator/update' endpoint.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: "Red is watching.",
    dateCommented: "2024-01-05",
    timeCommented: "01:44:26",
  },
  {
    id: 31,
    date: "2024-01-05",
    time: "01:43:58",
    level: "INFO",
    message:
      "Generator percentage requested using 'generator/percentage' endpoint. Percentage was 60%.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 32,
    date: "2024-01-05",
    time: "01:44:06",
    level: "INFO",
    message:
      "Substations values changed from 0 MW, 0 MW, and 0 MW to 5 MW, 4 MW, and 1 MW using 'substations/update' endpoint.",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 33,
    date: "2024-01-05",
    time: "01:44:08",
    level: "INFO",
    message:
      "Substations values requested using 'substations/values' endpoint. Values were 5 MW, 4 MW, and 1 MW",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 34,
    date: "2024-01-05",
    time: "01:43:55",
    level: "INFO",
    message:
      "Generator percentage changed from 0% to 60% using 'generator/update' endpoint.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: "Red is watching.",
    dateCommented: "2024-01-05",
    timeCommented: "01:44:26",
  },
  {
    id: 35,
    date: "2024-01-05",
    time: "01:43:58",
    level: "INFO",
    message:
      "Generator percentage requested using 'generator/percentage' endpoint. Percentage was 60%.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 36,
    date: "2024-01-05",
    time: "01:44:06",
    level: "INFO",
    message:
      "Substations values changed from 0 MW, 0 MW, and 0 MW to 5 MW, 4 MW, and 1 MW using 'substations/update' endpoint.",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 37,
    date: "2024-01-05",
    time: "01:44:08",
    level: "INFO",
    message:
      "Substations values requested using 'substations/values' endpoint. Values were 5 MW, 4 MW, and 1 MW",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 38,
    date: "2024-01-05",
    time: "01:43:55",
    level: "INFO",
    message:
      "Generator percentage changed from 0% to 60% using 'generator/update' endpoint.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: "Red is watching.",
    dateCommented: "2024-01-05",
    timeCommented: "01:44:26",
  },
  {
    id: 39,
    date: "2024-01-05",
    time: "01:43:58",
    level: "INFO",
    message:
      "Generator percentage requested using 'generator/percentage' endpoint. Percentage was 60%.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 40,
    date: "2024-01-05",
    time: "01:44:06",
    level: "INFO",
    message:
      "Substations values changed from 0 MW, 0 MW, and 0 MW to 5 MW, 4 MW, and 1 MW using 'substations/update' endpoint.",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 41,
    date: "2024-01-05",
    time: "01:44:08",
    level: "INFO",
    message:
      "Substations values requested using 'substations/values' endpoint. Values were 5 MW, 4 MW, and 1 MW",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 42,
    date: "2024-01-05",
    time: "01:43:55",
    level: "INFO",
    message:
      "Generator percentage changed from 0% to 60% using 'generator/update' endpoint.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: "Red is watching.",
    dateCommented: "2024-01-05",
    timeCommented: "01:44:26",
  },
  {
    id: 43,
    date: "2024-01-05",
    time: "01:43:58",
    level: "INFO",
    message:
      "Generator percentage requested using 'generator/percentage' endpoint. Percentage was 60%.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 44,
    date: "2024-01-05",
    time: "01:44:06",
    level: "INFO",
    message:
      "Substations values changed from 0 MW, 0 MW, and 0 MW to 5 MW, 4 MW, and 1 MW using 'substations/update' endpoint.",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 45,
    date: "2024-01-05",
    time: "01:44:08",
    level: "INFO",
    message:
      "Substations values requested using 'substations/values' endpoint. Values were 5 MW, 4 MW, and 1 MW",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 46,
    date: "2024-01-05",
    time: "01:43:55",
    level: "INFO",
    message:
      "Generator percentage changed from 0% to 60% using 'generator/update' endpoint.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: "Red is watching.",
    dateCommented: "2024-01-05",
    timeCommented: "01:44:26",
  },
  {
    id: 47,
    date: "2024-01-05",
    time: "01:43:58",
    level: "INFO",
    message:
      "Generator percentage requested using 'generator/percentage' endpoint. Percentage was 60%.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 48,
    date: "2024-01-05",
    time: "01:44:06",
    level: "INFO",
    message:
      "Substations values changed from 0 MW, 0 MW, and 0 MW to 5 MW, 4 MW, and 1 MW using 'substations/update' endpoint.",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 49,
    date: "2024-01-05",
    time: "01:44:08",
    level: "INFO",
    message:
      "Substations values requested using 'substations/values' endpoint. Values were 5 MW, 4 MW, and 1 MW",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 50,
    date: "2024-01-05",
    time: "01:43:55",
    level: "INFO",
    message:
      "Generator percentage changed from 0% to 60% using 'generator/update' endpoint.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: "Red is watching.",
    dateCommented: "2024-01-05",
    timeCommented: "01:44:26",
  },
  {
    id: 51,
    date: "2024-01-05",
    time: "01:43:58",
    level: "INFO",
    message:
      "Generator percentage requested using 'generator/percentage' endpoint. Percentage was 60%.",
    className: "com.example.ncdc.controller.GeneratorController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 52,
    date: "2024-01-05",
    time: "01:44:06",
    level: "INFO",
    message:
      "Substations values changed from 0 MW, 0 MW, and 0 MW to 5 MW, 4 MW, and 1 MW using 'substations/update' endpoint.",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
  {
    id: 53,
    date: "2024-01-05",
    time: "01:44:08",
    level: "INFO",
    message:
      "Substations values requested using 'substations/values' endpoint. Values were 5 MW, 4 MW, and 1 MW",
    className: "com.example.ncdc.controller.SubstationController",
    comment: null,
    dateCommented: null,
    timeCommented: null,
  },
];
